#######################################################################################
# Book settings

title: The Crisp-DM Model 
author: Almir Gouvea
logo: crisp-dm.png

#######################################################################################
# Execution settings

execute:
  execute_notebooks: off # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout: 600 # The maximum time (in seconds) each notebook cell is allowed to run.


#######################################################################################
# Launch button settings

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/almirgouvea/The-Crisp-DM-Model  # The URL to your book's repository
  branch: master  # Which branch of the repository should be used when creating links (optional)


#######################################################################################
# HTML-specific settings
html:
  navbar_number_sections: True  # Add a number to each section in your left navbar
  home_page_in_navbar: false  # Whether to include your home page in the left Navigation Bar
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
